version: '3'

services:

  db:
    image: postgres:13.0
    container_name: news-analyzer-db
    env_file:
      - ./deploy/.env.prod
    volumes:
      - news-analyzer-db-data:/var/lib/postgresql/data/
    networks:
      - news-analyzer-net

  cache:
    image: redis:6.2.6
    container_name: news-analyzer-cache
    networks:
      - news-analyzer-net

  api:
    build: .
    image: news-analyzer-api:0.0.1
    container_name: news-analyzer-api
    env_file:
      - ./deploy/.env.prod
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - WORKERS_NUM=2
      - POSTGRES_HOSTS=db
      - CACHE_TYPE=redis
      - REDIS_URL=redis://cache:6379/0
      - ECHO_DB=y
      - ECHO_POOL=y
    ports:
      - 8080:8080
    volumes:
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - db
      - cache
    networks:
      - news-analyzer-net

  data-loader:
    build: .
    image: news-analyzer-api:0.0.1
    container_name: task-processor
    env_file:
      - ./deploy/.env.prod
    environment:
      - POSTGRES_HOSTS=db
    entrypoint: dostoevsky download fasttext-social-network-model | news-analyzer-run-load-tasks
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    depends_on:
      - api
    networks:
      - news-analyzer-net


volumes:
  news-analyzer-db-data:

networks:
  news-analyzer-net: