"""props

Revision ID: 2e2d6cc2cf56
Revises: 240dd6e4aa03
Create Date: 2021-11-21 12:44:43.464784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e2d6cc2cf56"
down_revision = "240dd6e4aa03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("props", sa.JSON(), nullable=True))
    op.execute("UPDATE products SET props = '{}'::json WHERE props is NULL")
    op.alter_column("products", "props", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "props")
    # ### end Alembic commands ###
