"""fill_four_images

Revision ID: 3ff5efe4c628
Revises: 808a3403ef1a
Create Date: 2021-11-23 16:23:18.616849

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3ff5efe4c628"
down_revision = "808a3403ef1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    rows = connection.execute("SELECT id, images FROM products").fetchall()
    for product_id, images in rows:
        image = images[0]
        *_, ext = image.split(".")
        fn_without_ext = image[: -len(ext) - 1]

        for crop in range(4):
            images.append(f"{fn_without_ext}-{crop}.{ext}")

        connection.execute(
            sa.text("UPDATE products SET images= :images WHERE id= :id"),
            images=images,
            id=product_id,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE products set images = ARRAY[images[1]]")
    # ### end Alembic commands ###
