"""add links and mult images

Revision ID: 808a3403ef1a
Revises: fbfe57e2f1e4
Create Date: 2021-11-23 15:27:42.341750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "808a3403ef1a"
down_revision = "fbfe57e2f1e4"
branch_labels = None
depends_on = None

link = (
    "https://ru.wikipedia.org/wiki/%D0%9C%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D0%BB%"
    "D1%8C%D0%BD%D0%BE_%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D1%81%D0%BF%D0%BE%D1%81%"
    "D0%BE%D0%B1%D0%BD%D1%8B%D0%B9_%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("partners", sa.Column("link", sa.Text(), nullable=True))
    op.execute(f"UPDATE partners SET link = '{link}' WHERE link ISNULL")
    op.alter_column("partners", "link", nullable=False)

    op.add_column(
        "products",
        sa.Column("images", postgresql.ARRAY(sa.String(length=500)), nullable=True),
    )
    op.execute("UPDATE products SET images = ARRAY[products.image] WHERE images ISNULL")
    op.alter_column("products", "images", nullable=False)

    op.drop_column("products", "image")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("image", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("products", "images")
    op.drop_column("partners", "link")
    # ### end Alembic commands ###
