"""Init tables

Revision ID: b2b7c2c45598
Revises: 
Create Date: 2021-11-20 13:12:27.587998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2b7c2c45598"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partners",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, start=1), nullable=False
        ),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__partners")),
    )
    op.create_table(
        "products",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, start=1), nullable=False
        ),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("image", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__products")),
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, start=1), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_table(
        "offers",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, start=1), nullable=False
        ),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("old_price", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
            name=op.f("fk__offers__partner_id__partners"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk__offers__product_id__products"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__offers")),
    )
    op.create_table(
        "personal_offers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
            name=op.f("fk__personal_offers__offer_id__offers"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__personal_offers__user_id__users"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "offer_id", name=op.f("pk__personal_offers")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_offers")
    op.drop_table("offers")
    op.drop_table("users")
    op.drop_table("products")
    op.drop_table("partners")
    # ### end Alembic commands ###
