"""Initial

Revision ID: dc6c0386879e
Revises: 
Create Date: 2022-02-13 02:46:10.608825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc6c0386879e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles_sources",
        sa.Column(
            "src_id", sa.Integer(), sa.Identity(always=False, start=1), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "src_type", sa.Enum("rss", "file", name="textsourcetype"), nullable=True
        ),
        sa.Column("src", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("src_id", name=op.f("pk__articles_sources")),
        sa.UniqueConstraint("name", name=op.f("uq__articles_sources__name")),
    )
    op.create_table(
        "articles",
        sa.Column(
            "article_id",
            sa.Integer(),
            sa.Identity(always=False, start=1),
            nullable=False,
        ),
        sa.Column("src_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "neutral_sentiment",
            sa.Numeric(precision=6, scale=5, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "negative_sentiment",
            sa.Numeric(precision=6, scale=5, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "positive_sentiment",
            sa.Numeric(precision=6, scale=5, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "skip_sentiment",
            sa.Numeric(precision=6, scale=5, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "speech_sentiment",
            sa.Numeric(precision=6, scale=5, asdecimal=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["src_id"],
            ["articles_sources.src_id"],
            name=op.f("fk__articles__src_id__articles_sources"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("article_id", name=op.f("pk__articles")),
    )
    op.create_table(
        "named_entities",
        sa.Column(
            "entity_id",
            sa.Integer(),
            sa.Identity(always=False, start=1),
            nullable=False,
        ),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("LOC", "ORG", "PER", name="entitytype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
            name=op.f("fk__named_entities__article_id__articles"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk__named_entities")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("named_entities")
    op.drop_table("articles")
    op.drop_table("articles_sources")
    # ### end Alembic commands ###
