"""test

Revision ID: f40bb5ee0b2a
Revises: 2e2d6cc2cf56
Create Date: 2021-11-21 15:50:08.180449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f40bb5ee0b2a"
down_revision = "2e2d6cc2cf56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers",
        sa.Column("cashback_percent", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "offers",
        sa.Column("cashback_amount", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "personal_offers",
        sa.Column("cashback_percent", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "personal_offers",
        sa.Column("cashback_amount", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("personal_offers", "cashback_amount")
    op.drop_column("personal_offers", "cashback_percent")
    op.drop_column("offers", "cashback_amount")
    op.drop_column("offers", "cashback_percent")
    # ### end Alembic commands ###
